# Generated by Django 5.1.6 on 2025-02-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projmancoworking',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='projmancoworking',
            name='coworker_opinion',
        ),
        migrations.RemoveField(
            model_name='projmancoworking',
            name='illustration',
        ),
    ]
