# Generated by Django 5.1.6 on 2025-02-13 20:39

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projmancoworking',
            name='end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='projmancoworking',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='projmanproject',
            name='end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='projmanproject',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
