# Generated by Django 5.1.6 on 2025-02-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_alter_projmancoworking_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projmanproject',
            name='budget',
            field=models.PositiveIntegerField(),
        ),
    ]
