# Generated by Django 4.2.11 on 2025-02-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_projmancategory_image_projmancategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projmancategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
