# Generated by Django 4.2.11 on 2025-02-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure_Design', '0002_strcategory_image_strcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
