# Generated by Django 5.1.6 on 2025-02-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIMCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='bim/category')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BimPanelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='bim/banner')),
                ('image_title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('mini_title1', models.CharField(max_length=1000)),
                ('mini_title2', models.CharField(max_length=1000)),
                ('mini_title3', models.CharField(max_length=1000)),
                ('mini_description1', models.TextField()),
                ('mini_description2', models.TextField()),
                ('mini_description3', models.TextField()),
                ('slider1_description', models.TextField()),
                ('slider2_description', models.TextField()),
                ('slider3_description', models.TextField()),
                ('project_base_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BIMTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='training_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BIMCoworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='bim/video')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='bim/pdf')),
                ('illustration', models.TextField(blank=True, null=True)),
                ('characteristic', models.TextField(blank=True, null=True)),
                ('coworker_opinion', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='image/coworking')),
                ('architect', models.CharField(max_length=255)),
                ('structural_engineer', models.CharField(max_length=255)),
                ('contractor', models.CharField(max_length=255)),
                ('bim_software_used', models.CharField(max_length=255)),
                ('project_scale', models.CharField(choices=[('Small', 'کوچک'), ('Medium', 'متوسط'), ('Large', 'بزرگ')], max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('is_coordinated', models.BooleanField(default=False)),
                ('total_model_elements', models.IntegerField()),
                ('clash_detection_report', models.FileField(blank=True, null=True, upload_to='bim/reports/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BIM.bimcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BIMCoworkingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coworking_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('coworking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BIM.bimcoworking')),
            ],
        ),
        migrations.CreateModel(
            name='BIMProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='bim/video')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='bim/pdf')),
                ('image', models.ImageField(upload_to='image/project')),
                ('architect', models.CharField(max_length=255)),
                ('structural_engineer', models.CharField(max_length=255)),
                ('contractor', models.CharField(max_length=255)),
                ('bim_software_used', models.CharField(max_length=255)),
                ('project_scale', models.CharField(choices=[('Small', 'کوچک'), ('Medium', 'متوسط'), ('Large', 'بزرگ')], max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('is_coordinated', models.BooleanField(default=False)),
                ('total_model_elements', models.IntegerField()),
                ('clash_detection_report', models.FileField(blank=True, null=True, upload_to='bim/reports/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BIM.bimcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BIMProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BIM.bimproject')),
            ],
        ),
    ]
