# Generated by Django 5.1.6 on 2025-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimcoworking',
            name='content',
        ),
        migrations.AddField(
            model_name='bimcoworking',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimcoworking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimcoworking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimcoworking',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bim/pdf'),
        ),
        migrations.AddField(
            model_name='bimcoworking',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='bim/video'),
        ),
    ]
