# Generated by Django 5.1.6 on 2025-02-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0002_bimtraining_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimpanelmodel',
            name='coworking_banner1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cow_banner1', to='BIM.bimcoworking'),
        ),
        migrations.AddField(
            model_name='bimpanelmodel',
            name='coworking_banner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cow_banner2', to='BIM.bimcoworking'),
        ),
    ]
