# Generated by Django 5.1.6 on 2025-02-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0003_bimpanelmodel_coworking_banner1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimpanelmodel',
            name='coworking_banner1',
        ),
        migrations.RemoveField(
            model_name='bimpanelmodel',
            name='coworking_banner2',
        ),
        migrations.AddField(
            model_name='bimcoworking',
            name='banner',
            field=models.BooleanField(default=False),
        ),
    ]
