# Generated by Django 5.1.6 on 2025-02-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0004_remove_bimpanelmodel_coworking_banner1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimcoworking',
            name='banner',
        ),
    ]
