# Generated by Django 4.2.11 on 2025-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0006_bimpanelmodel_project_base_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimproject',
            name='content',
        ),
        migrations.AddField(
            model_name='bimproject',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
