# Generated by Django 4.2.11 on 2025-02-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0007_remove_bimproject_content_bimproject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimproject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='bim/video'),
        ),
        migrations.AddField(
            model_name='bimproject',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to='bim/image'),
        ),
    ]
