# Generated by Django 4.2.11 on 2025-02-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0008_bimproject_video_bimproject_video_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimproject',
            name='video_image',
        ),
    ]
