# Generated by Django 4.2.11 on 2025-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0009_remove_bimproject_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimproject',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bimproject',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
