# Generated by Django 4.2.11 on 2025-02-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0010_bimproject_latitude_bimproject_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimproject',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bim/pdf'),
        ),
    ]
