# Generated by Django 5.1.6 on 2025-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
