# Generated by Django 5.1.6 on 2025-02-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_usermodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('code', models.CharField(max_length=11, verbose_name='کد')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='انقضا')),
            ],
            options={
                'verbose_name': 'کد OTP',
                'verbose_name_plural': 'کد OTP',
            },
        ),
    ]
