# Generated by Django 5.1.6 on 2025-02-09 18:25

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.TextField()),
                ('about_us_description', models.TextField()),
                ('manager_fullname', models.CharField(max_length=100)),
                ('manager_position', models.TextField()),
                ('banner1', models.ImageField(blank=True, null=True, upload_to='about/image')),
                ('banner2', models.ImageField(blank=True, null=True, upload_to='about/image')),
                ('banner3', models.ImageField(blank=True, null=True, upload_to='about/image')),
                ('banner4', models.ImageField(blank=True, null=True, upload_to='about/image')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.TextField()),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SampleFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='sample/file')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('logo', models.ImageField(upload_to='site_detail/image')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('footer_text', models.TextField()),
                ('contact_us_text', models.TextField()),
                ('enamad_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('enamad_url', models.URLField(blank=True, null=True)),
                ('kasbokar_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('kasbokar_url', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
