# Generated by Django 5.1.6 on 2025-02-13 20:13

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BIM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('manager_fullname', models.CharField(max_length=100)),
                ('manager_position', models.TextField()),
                ('banner1', models.ImageField(upload_to='about/image')),
                ('banner2', models.ImageField(upload_to='about/image')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.TextField()),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SampleFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='sample/file')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('logo', models.ImageField(upload_to='site_detail/image')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('footer_text', models.TextField()),
                ('contact_us_text', models.TextField()),
                ('enamad_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('enamad_url', models.URLField(blank=True, null=True)),
                ('kasbokar_image', models.ImageField(blank=True, null=True, upload_to='site_detail/image')),
                ('kasbokar_url', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('banners_title', models.CharField(max_length=10000)),
                ('banners_text', models.TextField()),
                ('banner_image1', models.ImageField(upload_to='site_detail/image')),
                ('banner_image2', models.ImageField(upload_to='site_detail/image')),
                ('banner_image3', models.ImageField(upload_to='site_detail/image')),
                ('banner_image4', models.ImageField(upload_to='site_detail/image')),
                ('bim_banner_image', models.ImageField(upload_to='site_detail/image')),
                ('benefit_banner_image', models.ImageField(upload_to='site_detail/image')),
                ('bim_top_project_image', models.ImageField(upload_to='site_detail/image')),
                ('bim_top_project_description', models.TextField()),
                ('project_management_banner_image', models.ImageField(upload_to='site_detail/image')),
                ('retrofit_image', models.ImageField(upload_to='site_detail/image')),
                ('software_image', models.ImageField(upload_to='site_detail/image')),
                ('structure_design_image', models.ImageField(upload_to='site_detail/image')),
                ('project_management_video', models.FileField(upload_to='site_detail/video')),
                ('management_4d_image1', models.ImageField(upload_to='site_detail/image')),
                ('management_4d_image2', models.ImageField(upload_to='site_detail/image')),
                ('management_4d_image3', models.ImageField(upload_to='site_detail/image')),
                ('management_4d_image4', models.ImageField(upload_to='site_detail/image')),
                ('bim_top_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BIM.bimproject')),
            ],
        ),
    ]
