# Generated by Django 5.1.6 on 2025-02-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('banners_title', models.CharField(max_length=10000)),
                ('banners_text', models.TextField()),
                ('banner_image1', models.ImageField(upload_to='site_detail/image')),
                ('banner_image2', models.ImageField(upload_to='site_detail/image')),
                ('banner_image3', models.ImageField(upload_to='site_detail/image')),
                ('banner_image4', models.ImageField(upload_to='site_detail/image')),
                ('bim_banner_image', models.ImageField(upload_to='site_detail/image')),
                ('project_management_banner_image', models.ImageField(upload_to='site_detail/image')),
                ('retrofit_image', models.ImageField(upload_to='site_detail/image')),
                ('software_image', models.ImageField(upload_to='site_detail/image')),
                ('structure_design_image', models.ImageField(upload_to='site_detail/image')),
            ],
        ),
    ]
