# Generated by Django 4.2.11 on 2025-02-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecoworking',
            name='category',
        ),
        migrations.RemoveField(
            model_name='homecoworkingimage',
            name='coworking',
        ),
        migrations.RemoveField(
            model_name='homeproject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='homeprojectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='amazing_products_image',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='copy_right',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='empty_cart_image',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='footer_title',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='limit_of_address_can_add',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='samandehi_image',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='samandehi_url',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='suggested_products_image',
        ),
        migrations.RemoveField(
            model_name='sitedetailmodel',
            name='work_time',
        ),
        migrations.DeleteModel(
            name='HomeCategory',
        ),
        migrations.DeleteModel(
            name='HomeCoworking',
        ),
        migrations.DeleteModel(
            name='HomeCoworkingImage',
        ),
        migrations.DeleteModel(
            name='HomeProject',
        ),
        migrations.DeleteModel(
            name='HomeProjectImage',
        ),
    ]
