# Generated by Django 4.2.11 on 2025-02-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
