# Generated by Django 5.1.6 on 2025-02-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0002_indexdetailmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusdetailmodel',
            old_name='about_us_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='aboutusdetailmodel',
            old_name='about_us_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailmodel',
            name='banner3',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailmodel',
            name='banner4',
        ),
        migrations.AlterField(
            model_name='aboutusdetailmodel',
            name='banner1',
            field=models.ImageField(default=1, upload_to='about/image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutusdetailmodel',
            name='banner2',
            field=models.ImageField(default=1, upload_to='about/image'),
            preserve_default=False,
        ),
    ]
