# Generated by Django 4.2.11 on 2025-02-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0003_alter_contactusmodel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedetailmodel',
            old_name='about_us_text',
            new_name='about_us_description',
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='about_us_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='manager_fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='manager_position',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
