# Generated by Django 5.1.6 on 2025-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0004_indexdetailmodel_bim_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdetailmodel',
            name='bim_main_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
