# Generated by Django 5.1.6 on 2025-02-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0002_remove_bimcoworking_content_bimcoworking_description_and_more'),
        ('Home_Page', '0005_indexdetailmodel_bim_main_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexdetailmodel',
            old_name='bim_main_description',
            new_name='bim_top_project_description',
        ),
        migrations.RenameField(
            model_name='indexdetailmodel',
            old_name='bim_main_image',
            new_name='bim_top_project_image',
        ),
        migrations.AddField(
            model_name='indexdetailmodel',
            name='bim_top_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BIM.bimproject'),
        ),
    ]
