# Generated by Django 5.1.6 on 2025-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0006_rename_bim_main_description_indexdetailmodel_bim_top_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdetailmodel',
            name='benefit_banner_image',
            field=models.ImageField(default=1, upload_to='site_detail/image'),
            preserve_default=False,
        ),
    ]
