# Generated by Django 5.1.6 on 2025-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0008_indexdetailmodel_project_management_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdetailmodel',
            name='management_4d_image1',
            field=models.ImageField(default=1, upload_to='site_detail/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexdetailmodel',
            name='management_4d_image2',
            field=models.ImageField(default=1, upload_to='site_detail/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexdetailmodel',
            name='management_4d_image3',
            field=models.ImageField(default=1, upload_to='site_detail/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexdetailmodel',
            name='management_4d_image4',
            field=models.ImageField(default=1, upload_to='site_detail/image'),
            preserve_default=False,
        ),
    ]
