# Generated by Django 4.2.11 on 2025-02-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retrofit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrocategory',
            name='image',
            field=models.ImageField(default=1, upload_to='retro/category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retrocategory',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retrocoworking',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retroproject',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
