# Generated by Django 5.1.6 on 2025-02-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retrofit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrotraining',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
