# Generated by Django 5.1.6 on 2025-02-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='soft/category')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftPanelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='bim/banner')),
                ('image_title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('mini_title1', models.CharField(max_length=1000)),
                ('mini_title2', models.CharField(max_length=1000)),
                ('mini_title3', models.CharField(max_length=1000)),
                ('mini_description1', models.TextField()),
                ('mini_description2', models.TextField()),
                ('mini_description3', models.TextField()),
                ('slider1_description', models.TextField()),
                ('slider2_description', models.TextField()),
                ('slider3_description', models.TextField()),
                ('project_base_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SoftTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='training_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftCoworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='bim/video')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='bim/pdf')),
                ('illustration', models.TextField(blank=True, null=True)),
                ('characteristic', models.TextField(blank=True, null=True)),
                ('coworker_opinion', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='image/coworking')),
                ('version', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('supported_platforms', models.CharField(max_length=255)),
                ('license_type', models.CharField(choices=[('Free', 'رایگان'), ('Paid', 'پرداختی'), ('Subscription', 'اشتراکی')], max_length=100)),
                ('features', models.TextField()),
                ('official_website', models.URLField()),
                ('download_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Software.softcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftCoworkingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coworking_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('coworking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Software.softcoworking')),
            ],
        ),
        migrations.CreateModel(
            name='SoftProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='bim/video')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='bim/pdf')),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image/project')),
                ('version', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('supported_platforms', models.CharField(max_length=255)),
                ('license_type', models.CharField(choices=[('Free', 'رایگان'), ('Paid', 'پرداختی'), ('Subscription', 'اشتراکی')], max_length=100)),
                ('features', models.TextField()),
                ('official_website', models.URLField()),
                ('download_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Software.softcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Software.softproject')),
            ],
        ),
    ]
