# Generated by Django 5.1.6 on 2025-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softproject',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
