# Generated by Django 5.1.6 on 2025-02-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0002_softproject_description_softproject_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softcoworking',
            name='content',
        ),
        migrations.RemoveField(
            model_name='softproject',
            name='content',
        ),
    ]
